import { createZipWithFiles } from "./generate-zip";

/**
 * Give file information and create a kmp file for the dictionary
 *
 * Format of the lexical model file: {model_id}.model.js
 * the compiled code generated by the @predictive-text-studio/lexical-model-compiler
 *
 * @param modelID
 * @param compiledModelCode
 * @param modelInfo
 */
export async function generateKmp(
  modelID: string,
  compiledModelCode: string,
  modelInfo: string
): Promise<ArrayBuffer> {
  const kmpFile = createZipWithFiles({
    [`${modelID}.model.js`]: compiledModelCode,
    "kmp.json": modelInfo,
  });
  return kmpFile;
}
