/**
 * @file Interfaces used in storage
 */

import type { WordListSource, StoredProjectData } from "@common/types";

export interface StoredWordList extends WordListSource {
  /** Autogenerated primary key */
  id?: number;
}

export interface KeyboardData {
  /*
   * Store bcp47Tag as the primarykey
   */
  bcp47Tag: string;
  /**
   * Keyboard Language of the bcp47Tag
   */
  language: string;
}
export interface KeyboardDataWithTime extends KeyboardData {
  /**
   * Timestamp of last updated time
   */
  timestamp: Date;
}
export interface KMPPackageData {
  /** Autogenerated primary key */
  id?: number;
  /** The compiled KMP package */
  package: ArrayBuffer;
}

export interface ExportedProjectData {
  projectData: StoredProjectData;
  files: WordListSource[];
}
