/**
 * @file Interfaces used in storage
 */

import type { WordListSource, ProjectMetadata } from "@common/types";

export interface StoredWordList extends WordListSource {
  /** Autogenerated primary key */
  id?: number;
}

/**
 * The information needed to create a KMP file
 */
export interface StoredProjectData extends ProjectMetadata {
  /**
   * Primary key. For now, there is only one project, with PACKAGE_ID as its
   * primary key.
   */
  id?: number;

  /**
   * A custom model ID string.
   */
  modelID?: string;

  /**
   * The version number of the model.
   */
  version?: string;
}

export interface KeyboardData {
  /*
   * Store bcp47Tag as the primarykey
   */
  bcp47Tag: string;
  /**
   * Keyboard Language of the bcp47Tag
   */
  language: string;
}
export interface KeyboardDataWithTime extends KeyboardData {
  /**
   * Timestamp of last updated time
   */
  timestamp: Date;
}
export interface KMPPackageData {
  /** Autogenerated primary key */
  id?: number;
  /** The compiled KMP package */
  package: ArrayBuffer;
}

export interface ExportedProjectData {
  projectData: StoredProjectData;
  files: WordListSource[];
}
