import type { WordList } from "@common/types";
export interface DictionarySource {
  name: string;
  size: number;
  type: string;
}
export interface StoredWordList {
  /** Autogenerated primary key */
  id?: number;

  /**
   * Typically the filename of the uploaded dictionary source.
   */
  name: string;
  /**
   * The actual contents of said file.
   */
  wordlist: WordList;
  /**
   * Size of the file in bytes.
   */
  size?: number;
  /**
   * File extension.
   */
  type?: string;
}
